name: ubuntu-bug-triage
summary: Recently updated Launchpad bugs for triage
description: |
  Recently updated Launchpad bugs for triage. User provides a source
  package or a package team to search bugs for. By default, will
  provide yesterday's bugs for triage or the user can provide a
  different day or even a date range.

version: git
grade: stable
confinement: strict
architectures:
    - amd64
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ubuntu-bug-triage:
        command: bin/ubuntu-bug-triage
        plugs:
            - browser-support
            - desktop
            - network
            - network-bind

parts:
    ubuntu-bug-triage:
        plugin: python
        source: https://github.com/powersj/ubuntu-bug-triage
        source-type: git
